workspace 'News.xcworkspace'

install! 'cocoapods', :generate_multiple_pod_projects => true

def common_umbrella_pod
    pod 'CommonUmbrella', :path => '../../common/umbrella'
end

def local_pod(name, **kwargs)
  kwargs[:path] = "./Modules/#{name}"
  pod name, kwargs
end

target 'News' do
  project 'News.xcodeproj'
  platform :ios, '12.0'
  
  # Feature modules
  local_pod 'DivkitFeature'
  local_pod 'DivkitCustomFeature'
  local_pod 'SearchFeature'
  
  local_pod 'BaseUiKit'

  common_umbrella_pod
end
